#%RAML 1.0
title: api-raml-template
version: v1


  
/health:
  get:
    displayName: resource to check the health of the underlying systems
    responses:
      200:
        body:
          application/json:
            example: !include example/getHealthResponseExample.json  
